# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-17 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nisn', models.CharField(max_length=200)),
                ('nama', models.CharField(max_length=200)),
            ],
        ),
    ]
